---
name: actionlint
on:
  push:
    branches: [main]
    paths:
      - .github/**
  pull_request:
    branches: [main]
    paths:
      - .github/**
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
      - uses: aquaproj/aqua-installer@9cab8158a28544f74e1c45ee13a6d49fa1082811 # v2.0.0
        with:
          aqua_version: v1.26.1
      - run: actionlint
