---
name: test (workflow_call)
on: workflow_call
permissions: {}
jobs:
  path-filter:
    # Get changed files to filter jobs
    timeout-minutes: 10
    outputs:
      renovate-config-validator: ${{steps.changes.outputs.renovate-config-validator}}
      ghalint: ${{steps.changes.outputs.ghalint}}
      preset: ${{steps.changes.outputs.preset}}
      changed_presets_files: ${{steps.changes.outputs.changed_presets_files}}
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          list-files: shell
          filters: |
            renovate-config-validator:
              - renovate.json5
              - .github/workflows/workflow_call_renovate_config_validator.yaml
            preset:
              - "*.json"
              - ./.github/workflows/workflow_call_validate_presets.yaml
            changed_presets:
              - "*.json"
            ghalint:
              - .github/workflows/*.yaml
              - aqua/ghalint.yaml

  renovate-config-validator:
    needs: path-filter
    if: needs.path-filter.outputs.renovate-config-validator == 'true'
    uses: ./.github/workflows/workflow_call_renovate_config_validator.yaml
    permissions:
      contents: read

  validate-presets:
    needs: path-filter
    if: needs.path-filter.outputs.preset == 'true'
    uses: ./.github/workflows/workflow_call_validate_presets.yaml
    with:
      files: ${{ needs.path-filter.outputs.changed_presets_files }}

  ghalint:
    needs: path-filter
    if: needs.path-filter.outputs.ghalint == 'true'
    uses: ./.github/workflows/workflow_call_ghalint.yaml
