---
name: Validate Presets
on:
  workflow_call:
    inputs:
      files:
        type: string
        required: true
jobs:
  validate-presets:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          # node-version: 24.1.0
          node-version: 22.23.1
      - env:
          FILES: ${{ inputs.files }}
        run: |
          if [ -z "$FILES" ]; then
            FILES=default.json
          fi
          echo "$FILES" | while read -r file; do
            if [ -f "$file" ]; then
              RENOVATE_CONFIG_FILE="$file" npx --package renovate -c renovate-config-validator
            fi
          done
